# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-26 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookNo', models.IntegerField(blank=True, null=True, verbose_name='Book No')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='سال')),
                ('page', models.CharField(blank=True, max_length=20, null=True, verbose_name='صفحه')),
                ('image', models.ImageField(default='no-image.jpg', upload_to='book/images/', verbose_name='Book image')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='توضیحات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشر ها',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
            ],
            options={
                'verbose_name': 'مترجم',
                'verbose_name_plural': 'مترجم ها',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Translator', verbose_name='مترجم'),
        ),
    ]
