# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigations.Navigation', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Navgation',
                'verbose_name_plural': 'Navgations',
            },
        ),
    ]
