# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200112_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='article/images/', verbose_name='Article image'),
        ),
    ]
